const ARCHETYPES_CONTENT = {
  captainSustainables: {
    name: 'Captain Sustainables',
    icon: '♻️',
    tagline: 'Leads with action. Systems that last.',
    description: 'You are a builder at heart. You see the world not just as it is, but as it could be — greener, fairer, and more efficient. You thrive in community settings, rallying people around shared goals and turning good intentions into lasting habits and infrastructure that outlive any single effort.',
    strengths: ['Organised', 'Collaborative', 'Systems thinker', 'Pragmatic'],
    impact: 'You create change that compounds. Where others see a one-off event, you see the seed of a movement. Your ability to design systems — recycling programmes, community gardens, green procurement policies — means your impact keeps growing long after you have moved on.',
    nextStep: 'Map one habit in your daily life that could become a community programme. Start small, document it, and share the results.',
    image: 'images/captain-sustainables.jpg',
    imageAlt: 'Captain Sustainables — a community builder in action',
    accentColor: '#4a7c59',
  },
  warriorOfTheWild: {
    name: 'Warrior of the Wild',
    icon: '🌲',
    tagline: 'Leads with courage. The wild calls.',
    description: 'You feel most alive when you are in nature. You have a fierce, protective instinct for wild places and the creatures that inhabit them. You are not afraid to speak up, show up, or get your hands dirty in defence of biodiversity — even when it is inconvenient or unpopular.',
    strengths: ['Passionate', 'Resilient', 'Hands-on', 'Protective'],
    impact: 'You are the voice for those who cannot speak for themselves. Your presence in the field — documenting, restoring, advocating — creates a living record of what is worth protecting. You remind people that nature is not a backdrop; it is the foundation.',
    nextStep: 'Visit a local nature reserve this weekend. Bring a notebook. Write down one thing you want to protect, and one concrete action you can take.',
    image: 'images/warrior-of-the-wild.jpg',
    imageAlt: 'Warrior of the Wild — a defender of nature and biodiversity',
    accentColor: '#2c4a2e',
  },
  drEnvironlove: {
    name: 'Dr. Environlove',
    icon: '🔬',
    tagline: 'Leads with mind. Data drives real change.',
    description: 'You believe that understanding a problem deeply is the first step to solving it. You read the research, follow the science, and trust evidence over emotion. Your analytical approach helps cut through noise and focus effort where it matters most — not just where it feels good.',
    strengths: ['Analytical', 'Curious', 'Evidence-driven', 'Innovative'],
    impact: 'You give the environmental movement its backbone. Without rigorous data and honest analysis, well-meaning efforts can miss the mark. You ensure that resources go where they will do the most good, and that progress can actually be measured.',
    nextStep: 'Find one environmental claim you have accepted without checking. Look up the primary source. Share what you learn with someone who would find it useful.',
    image: 'images/dr-environlove.jpg',
    imageAlt: 'Dr. Environlove — a scientist and environmental researcher',
    accentColor: '#7aab8a',
  },
  sirAnimalot: {
    name: 'Sir Animalot',
    icon: '🐾',
    tagline: 'Leads with heart. Every creature deserves care.',
    description: 'You are driven by compassion. When an animal is in need, you are the first to act — not because you have to, but because you cannot imagine doing otherwise. Your empathy is your greatest strength, and it inspires everyone around you to care more deeply about the living world.',
    strengths: ['Empathetic', 'Nurturing', 'Action-oriented', 'Community connector'],
    impact: 'You make the abstract personal. Climate change, habitat loss, and biodiversity collapse are easier to ignore when they feel distant — but you bring them close. Through the animals you care for and the stories you tell, you help people feel the stakes.',
    nextStep: 'Reach out to a local animal welfare organisation this week. Even one hour of volunteering can shift your perspective and open new doors.',
    image: 'images/sir-animalot.jpg',
    imageAlt: 'Sir Animalot — a compassionate animal welfare advocate',
    accentColor: '#8c6d3f',
  },
};
