const ARCHETYPES_CONTENT = {
  captainSustainables: {
    name: 'Captain Sustainables',
    icon: '♻️',
    tagline: 'Leads with action. Systems that last.',
    description: 'You see how everyday things can be interconnected, and the ripple effects that even the smallest habits can cause. “Sustainability” to you is more than just a buzzword, it is a system. You actively think about improving the status quo and making things more green-efficient.',
    strengths: ['Organised', 'Collaborative', 'Pragmatic'],
    impact: 'You organise, plan and integrate. Precisely because you see how the little actions and patterns build up to the eventual results, that is why you are able to effectively link various eco-causes into a holistic system that lasts.',
    image: 'assets/cpts.png',
    sceneImage: 'assets/cpts-bg.png',
    imageAlt: 'Captain Sustainables archetype character illustration',
    accentColor: '#4a7c59',
  },
  warriorOfTheWild: {
    name: 'Warrior of the Wild',
    icon: '🌲',
    tagline: 'Leads with courage. The wild calls.',
    description: 'You are a champion of the wilderness. With a campaigner\'s spirit, you fight for the rights of the wildlife around you, advocating even for unpopular opinions. You view the vibrant biodiversity around you with amity, and feel most at ease when surrounded by wildlife.',
    strengths: ['Passionate', 'Resilient', 'Hands-on'],
    impact: 'You are the voice for the wildlife that cannot speak for themselves; fighting for their needs and survival. Unafraid of getting down and dirty, you are ready to be on-the-ground at forests and nature reserves, learning and understanding about the various species in our City in Nature.',
    image: 'assets/wow.png',
    sceneImage: 'assets/wow-bg.png',
    imageAlt: 'Warrior of the Wild archetype character illustration',
    accentColor: '#2c4a2e',
  },
  drEnvironlove: {
    name: 'Dr. Environlove',
    icon: '🔬',
    tagline: 'Leads with mind. Data drives real change.',
    description: 'You believe that researching deeply into the eco-causes we are passionate about is of paramount importance. Surrounding yourself with nature, your greatest joy comes from being able to better understand the ecosystems around us and how we shape our lands in our City in Nature.',
    strengths: ['Analytical', 'Curious', 'Innovative'],
    impact: 'You support the environmental movement with your expansive knowledge and intensive research. While others may consider active advocacy and building multidisciplinary platforms, you prefer to take the backend and produce the necessary data and analyses to support the cause.',
    image: 'assets/de.png',
    sceneImage: 'assets/de-bg.png',
    imageAlt: 'Dr. Environlove archetype character illustration',
    accentColor: '#7aab8a',
  },
  sirAnimalot: {
    name: 'Sir Animalot',
    icon: '🐾',
    tagline: 'Leads with heart. Every creature deserves care.',
    description: 'You possess a heart of compassion. Actively looking out for the animals, you ensure that all stray or displaced are well taken care of in our City in Nature. A true protector, you are the first to act when an animal is in peril, maintaining peace and harmony.',
    strengths: ['Empathetic', 'Nurturing', 'Community connector'],
    impact: 'While others may seek for efficient systems and ecosystem restoration, you look deeper into the individual animals that require our care. Emphasising deeper engagements, you are the heroes that volunteer at animal shelters, and the protectors who encourage communities to empathise with the animals around us.',
    image: 'assets/sani.png',
    sceneImage: 'assets/sani-bg.png',
    imageAlt: 'Sir Animalot archetype character illustration',
    accentColor: '#8c6d3f',
  },
};
